version: '3'
services:
  api:
    build: api/
    container_name: kys-api
    ports:
      - "8000:8000"
    environment:
      - "IAM_ROLE_ARN=arn:aws:iam::533267194514:role/LabRole"
      - "APP_BUCKET_NAME=kys-session-files-5a7e3de160b99067"
      - "APP_TABLE_NAME=kys-sessions"
      - "USER_POOL_ARN=arn:aws:cognito-idp:us-east-1:533267194514:userpool/us-east-1_MAmMnwJoy"
    networks:
      - kys-dev-stack
    volumes:
      - ./api:/api # Maps local API directory to /api in the container

  web:
    container_name: kys-web
    build: web/
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEB_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - region=us-east-1
      - USER_POOL_CLIENT_ID=2t46jv3su0a8spt1cpd39ed2um
    networks:
      - kys-dev-stack
    volumes:
      - ./web:/app # Maps local web directory to /app in the container

networks:
  kys-dev-stack:
    driver: bridge
